---
- name: Install microk8s and kubectl
  become: true
  hosts: all
  tasks:
    - name: Install
      community.general.snap:
        classic: true
        channel: 1.31
        name:
          - microk8s
          - kubectl

- name: Preparing User
  become: true
  hosts: all
  tasks:
    - name: Add user to microk8s group
      ansible.builtin.user:
        name: "{{ vm_username }}"
        groups: microk8s
        append: true
    - name: Reset connection
      ansible.builtin.meta: reset_connection

- name: Change kube folder ownership
  become: true
  hosts: all
  tasks:
    - name: Change ownership
      ansible.builtin.file:
        path: /home/{{ vm_username }}/.kube
        owner: "{{ vm_username }}"
        group: "{{ vm_username }}"
        state: directory
        mode: "0700"

- name: Enable microk8s common modules
  become: true
  hosts: all
  tasks:
    - name: Enable module
      ansible.builtin.command: microk8s enable {{ item }}
      loop: "{{ microk8s_modules }}"
      changed_when: false

- name: Create local kubeconfig
  become: true
  hosts: all
  tasks:
    - name: Run microk8s config command
      ansible.builtin.command: microk8s config
      register: microk8s_config_output
      changed_when: false
    - name: Write microk8s config to kubeconfig file
      ansible.builtin.copy:
        content: "{{ microk8s_config_output.stdout }}"
        dest: /home/{{ vm_username }}/.kube/config
        owner: "{{ vm_username }}"
        group: "{{ vm_username }}"
        mode: "0600"

- name: Setup k8s
  become: true
  hosts: all
  tasks:
    - name: Setup LoadBalancer for NGINX
      ansible.builtin.command: microk8s kubectl apply -f "{{playbook_dir}}/files/loadbalancer.yaml"
      changed_when: false
    - name: Prepare Grafana Ingress
      ansible.builtin.template:
        src: "{{playbook_dir}}/files/ingress.yaml.j2"
        dest: "{{playbook_dir}}/files/ingress.yaml"
        mode: "0600"
    - name: Setup Grafana Ingress
      ansible.builtin.command: microk8s kubectl apply -f "{{playbook_dir}}/files/ingress.yaml"
      changed_when: false
